audiotest: Fix Wformat warnings reported by clang.
Fix a bunch of warnings reported by clang because of incorrect
format specifiers.

/mnt/host/source/src/platform/audiotest/src/alsa_conformance_helper.c:159:40: error: format specifies type
'int' but the argument has type 'snd_pcm_uframes_t' (aka 'unsigned long') [-Werror,-Wformat]
     printf("period size: %d frames\n", frames);
                         ~~            ^~~~~~
                         %lu
/mnt/host/source/src/platform/audiotest/src/alsa_conformance_helper.c:173:40: error: format specifies type
'unsigned int' but the argument has type 'snd_pcm_uframes_t' (aka 'unsigned long') [-Werror,-Wformat]
    printf("buffer size: %u frames\n", frames);
                         ~~            ^~~~~~
                         %lu
/mnt/host/source/src/platform/audiotest/src/alsa_conformance_helper.c:283:67: error: invalid conversion
specifier ':' [-Werror,-Wformat-invalid-specifier]
         fprintf(stderr, "snd_pcm_hw_params_set_period_size_near %l: %s\n",
                                                                ~~^
/mnt/host/source/src/platform/audiotest/src/alsa_conformance_helper.c:284:17: error: format specifies type
'char *' but the argument has type 'snd_pcm_uframes_t' (aka 'unsigned long') [-Werror,-Wformat]
                 *period_size, snd_strerror(rc));
                ^~~~~~~~~~~~
/mnt/host/source/src/platform/audiotest/src/alsa_conformance_helper.c:284:31: error: data argument not
used by format string [-Werror,-Wformat-extra-args]
                 *period_size, snd_strerror(rc));

And several more.

BUG=chromium:958583
TEST=emerge-amd64-generic audiotest works.

Change-Id: Id5bcb98877e83bf15a4c00d43c29b5963cd3c015
Reviewed-on: https://chromium-review.googlesource.com/1592641
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>